
services:
  - type: web
    name: smartflow-solutions
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    # This ensures that all routes are handled by the SPA
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
